extra_css:
  - https://qihang-zhang.github.io/customized_mkdocs/stylesheets/extra.css

extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true  
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes

extra_javascript:
  # - https://qihang-zhang.github.io/customized_mkdocs/extra_javascript/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - bibtex:
      bib_file: 'docs/assets/references.bib'
  - blog:
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      # authors: true
      authors_file: "{blog}/.authors.yml"
      draft: true
      draft_on_serve: true
      draft_if_future_date: false
  - meta
  - tags
  - info:
      enabled: false
      enabled_on_serve: true
      archive: false
      archive_stop_on_violation: false
  - offline
  # - offline:
  #     enabled: !ENV [OFFLINE, false]

theme:
  name: material
  features:
    - katex
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - toc.integrate
    - navigation.sections
    - content.code.copy
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3


  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

