alias copy_mkdocs_config="./customized_mkdocs/maintain_config/copy_config.sh"
alias remove_mkdocs_config="./customized_mkdocs/maintain_config/remove_config.sh"
alias mk_preview="./customized_mkdocs/mkdocs_preview.sh"
alias mk_publish="./customized_mkdocs/mkdocs_publish.sh"

echo "------------------------------------------------------------------------"
echo "use the following commands to manage the blog"
echo "------------------------------------------------------------------------"
echo "mk_preview: preview the blog"
echo "mk_publish: publish the blog"
echo "------------------------------------------------------------------------"
echo "copy_mkdocs_config: copy the config files to the blog"
echo "remove_mkdocs_config: remove the config files from the blog"
echo "------------------------------------------------------------------------"